name: "FAP: Build for multiple SDK sources and lint"

on:
  push:
  pull_request:
  schedule:
    # do a build every day
    - cron: "0 3 * * *"

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk-channel: [dev, release]
        app-dir: [mode7_demo]
    name: 'ufbt: Link and build ${{ matrix.app-dir }} for ${{ matrix.sdk-channel }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint sources
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          task: lint
          app-dir: ${{ matrix.app-dir }}
      - name: Build with uFBT
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          skip-setup: true
          task: build
          sdk-channel: ${{ matrix.sdk-channel }}
          app-dir: ${{ matrix.app-dir }}
      - name: Upload app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}
