name: "FAP: Build for multiple SDK sources and lint"

on:
  push:
  pull_request:
  schedule:
    # do a build every day
    - cron: "0 3 * * *"

jobs:
  lint-sources:
    runs-on: ubuntu-latest
    name: 'ufbt: Lint sources'
    if: github.event_name != 'schedule'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint sources
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          task: lint

  ufbt-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: dev channel
            sdk-channel: dev
          - name: release channel
            sdk-channel: release
    name: 'ufbt: Build for ${{ matrix.name }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with uFBT
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          sdk-channel: ${{ matrix.sdk-channel }}
      - name: Upload app artifacts
        uses: actions/upload-artifact@v4
        with:
          # See ufbt action docs for other output variables
          name: ${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}
